apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

transformers:
  - |
    apiVersion: builtin
    kind: PrefixTransformer
    metadata:
      name: inline-prefix
    prefix: v2-inline-
    fieldSpecs:
      - path: metadata/name