apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: test-labs-6
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
      nodePort: 30001
  selector:
    app: wordpress
  type: NodePort
